#!/bin/bash
# Usage: swagger <specLink> [outputFileName]

if [[ "$1" == "" ]]; then
	echo ERROR: You must a link to the spec to generate
	echo
fi

# Print usage, if requested / necessary
if [[ "$1" == "" || "${1//-/}" == "usage" || "${1//-/}" == "help" || "${1//-/}" == "?" ]]; then
	echo "This command runs a generator against a swagger spec json file to output an AngularJS REST client"
	echo 
	echo "    Usage:     swagger <linkToSwaggerSpecJson> [outputFile=angular-rest-client.js]"
	echo
	echo "        swaggerSpecLink   (required)    A link to the swagger spec to generate into AngularJS code" 
	echo "        outputFileName    (optional)    The name of the generated AngularJS file to save"
	echo 
	echo
	echo "    Example:   swagger generate-angular.js swagger-spec.json output.js"
	exit 1;
fi

# Set or use default outputFileName
if [[ "$2" == "" ]]; then
	export OUTPUTFILE=angular-rest-client.js
else
	export OUTPUTFILE=$2
fi

# Grab the newest swagger spec
echo "Downloading newest Swagger spec from $1:"
sudo curl -L $1 > swagger-spec.json

# Generate our REST API from this spec using swagger-js-codegen
echo "Generating AngularJS REST API..."
docker run --rm -it -v `pwd`:/data bodom0015/nodejs-bower-grunt node generate-angular.js > ${OUTPUTFILE}

echo "Done!"
